#!/bin/bash

mkdir build

(cd ./source && cp -r . ../build)
(cd ./submission && cp -r . ../build)

ls ./submission > submission_files.txt

cd build

make > build_output.txt 2>&1 || {
  cat build_output.txt
  cp ./error_template.json ../results/results.json
  exit 1
}

./runner

clang-tidy --config-file=./clang-tidy -warnings-as-errors=* $(cat ../submission_files.txt) 2> /dev/null > clang_tidy_output.txt
lintercode=$?

python3 result_parser.py \
  --output output.json \
  --linter clang_tidy_output.txt \
  --lintercode $lintercode \
  --linterpoints 5 > ../results/results.json